// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEtIVu13L7rT5d0-9Z2h3wGaHLWb55f6I',
    appId: '1:810761842263:web:076d2769c3371f1a043d12',
    messagingSenderId: '810761842263',
    projectId: 'fir-f8843',
    authDomain: 'fir-f8843.firebaseapp.com',
    storageBucket: 'fir-f8843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLQkJRUiBsd79klP0axQfCWgIi_TezZhk',
    appId: '1:810761842263:android:878880d317cd87e6043d12',
    messagingSenderId: '810761842263',
    projectId: 'fir-f8843',
    storageBucket: 'fir-f8843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7lHHFGb5rQSzeF3pKEZv-dZWQe1GPME',
    appId: '1:810761842263:ios:b0f777b2ae08bbf1043d12',
    messagingSenderId: '810761842263',
    projectId: 'fir-f8843',
    storageBucket: 'fir-f8843.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7lHHFGb5rQSzeF3pKEZv-dZWQe1GPME',
    appId: '1:810761842263:ios:2a0d0688bf6c8643043d12',
    messagingSenderId: '810761842263',
    projectId: 'fir-f8843',
    storageBucket: 'fir-f8843.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
